#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp
yabai -m config auto_balance on

yabai -m config top_padding 7		
yabai -m config bottom_padding 7		
yabai -m config left_padding 7
yabai -m config right_padding 7		
yabai -m config window_gap 7		

yabai -m config window_placement second_child
yabai -m config split_ratio 0.50

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Photo Booth$" manage=off
